# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TVShows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows
  pod 'SVProgressHUD', '~> 2.2'
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod 'Kingfisher', '~> 4.0'

  target 'TVShowsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVShowsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

 
